export const mockAudits = [
  {
    id: "a1",
    title: "Q3 2026 Financial Controls",
    type: "Financial",
    status: "Fieldwork",
    progress: 45,
    risk: "High",
    startDate: "2026-07-01",
    endDate: "2026-08-15",
    lead: "Sarah Jenkins",
    team: ["David Chen", "Elena Rodriguez"],
  },
  {
    id: "a2",
    title: "ISO 27001 Compliance Review",
    type: "Compliance",
    status: "Planning",
    progress: 10,
    risk: "Critical",
    startDate: "2026-07-15",
    endDate: "2026-09-01",
    lead: "Michael Chang",
    team: ["David Chen"],
  },
  {
    id: "a3",
    title: "Vendor Management Process",
    type: "Operational",
    status: "Review",
    progress: 90,
    risk: "Medium",
    startDate: "2026-05-10",
    endDate: "2026-07-05",
    lead: "Elena Rodriguez",
    team: ["Sarah Jenkins"],
  },
  {
    id: "a4",
    title: "IT General Controls - Cloud Infrastructure",
    type: "IT",
    status: "Reporting",
    progress: 95,
    risk: "High",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    lead: "David Chen",
    team: ["Michael Chang"],
  }
]

export const mockFindings = [
  {
    id: "f1",
    auditId: "a4",
    title: "Inadequate AWS Security Group Configurations",
    severity: "Critical",
    status: "Open",
    owner: "DevOps Team",
    dueDate: "2026-07-15",
  },
  {
    id: "f2",
    auditId: "a3",
    title: "Missing Vendor Due Diligence for 3 Key Suppliers",
    severity: "High",
    status: "Management Response",
    owner: "Procurement",
    dueDate: "2026-07-10",
  },
  {
    id: "f3",
    auditId: "a1",
    title: "Manual Journal Entry Approval Bypassed",
    severity: "High",
    status: "Draft",
    owner: "Finance",
    dueDate: "2026-08-01",
  },
  {
    id: "f4",
    auditId: "a3",
    title: "Inconsistent Contract Storage",
    severity: "Medium",
    status: "In Remediation",
    owner: "Legal",
    dueDate: "2026-08-15",
  },
]
